---
abstract: 'Form validation and refilling'
author:
  - 'Chisel <chisel@chizography.net>'
build_requires:
  Catalyst: 0
  Catalyst::Plugin::FillInForm: 0
  Catalyst::View::HTML::Template: 0
  Catalyst::View::TT: 0
  Class::C3: 0
  Class::Inspector: 0
  Data::FormValidator::Constraints: 0
  FindBin: 0
  Test::More: 0
  Test::UseAllModules: 0
  Test::WWW::Mechanize::Catalyst: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-Validation-DFV
requires:
  Carp: 0
  Catalyst::Controller: 0
  Catalyst::Plugin::FillInForm: 0
  Data::FormValidator: 0
  Data::FormValidator::Constraints: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Catalyst-Controller-Validation-DFV
  repository: git://github.com/chiselwright/catalyst-validation-dfv.git
version: 0.0.8
